telegram_token = "***REMOVED***"
telegram_url = "https://api.telegram.org/bot***REMOVED***/"
database_url = "***REMOVED***"
app_url = "https://vast-ravine-49209.herokuapp.com"

client_id = "***REMOVED***"
client_secret = "***REMOVED***"
access_token = "***REMOVED***"
refresh_token = "***REMOVED***"
album_id = "***REMOVED***"